return {
  settings = {
    Lua = {
      diagnostics = {
        globals = { "vim" },
      },
      format = {
        enabled = true,
        defaultConfig = {
          indent_style = "space",
          indent_size = "2",
          quote_style = "none",
          call_arg_parentheses = "keep",
          continuation_indent = "4",
          max_line_length = "120",
          trailing_table_seperator = "smart",
          insert_final_newline = "true",
          space_around_table_field_list = "true",
          space_before_attribute = "true",
          space_before_function_open_parenthesis = "false",
          space_before_function_call_open_parenthesis = "false",
          space_before_closure_open_parenthesis = "false",
          space_before_function_call_single_arg = "true",
          space_before_open_square_bracket = "false",
          space_inside_function_call_parentheses = "true",
          space_inside_function_param_list_parentheses = "true",
          space_inside_square_brackets = "true",
          space_around_table_append_operator = "false",
          ignore_spaces_inside_function_call = "false",
          space_before_inline_comment = "1",
          space_around_math_operator = "true",
          space_after_comma = "true",
          space_after_comma_in_for_statement = "true",
          space_around_concat_operator = "true",
          align_call_args = "true",
          align_function_params = "true",
          align_continuous_assign_statement = "true",
          align_continuous_rect_table_field = "true",
          align_if_branch = "true",
          align_array_table = "true",
          never_indent_before_if_condition = "true",
          never_indent_comment_on_if_branch = "true",
          line_space_after_if_statement = "fixed(2)",
          line_space_after_do_statement = "fixed(2)",
          line_space_after_while_statement = "fixed(2)",
          line_space_after_repeat_statement = "fixed(2)",
          line_space_after_for_statement = "fixed(2)",
          line_space_after_local_or_assign_statement = "max(2)",
          line_space_after_function_statement = "fixed(2)",
          line_space_after_expression_statement = "fixed(1)",
          line_space_after_comment = "fixed(1)",
          break_all_list_when_line_exceed = "false",
          auto_collapse_lines = "false",
          ignore_space_after_colon = "false",
          remove_call_expression_list_finish_comma = "false",
        }
      },
      workspace = {
        library = {
          [ vim.fn.expand( "$VIMRUNTIME/lua" ) ] = true,
          [ vim.fn.stdpath( "config" ) .. "/lua" ] = true,
        },
      },
    },
  },
}
